/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HA1.app;

import HA1.list.LinkedList;

import static HA1.utilities.StringUtils.join;
import static HA1.utilities.StringUtils.split;
import static HA1.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
